apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mywebapp
  name: mywebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mywebapp
    spec:
      containers:
      - image: yahyaalshamrani/mywebapp:v0.1
        name: mywebapp
        ports:
        - containerPort: 8080
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mywebapp
  name: mywebapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mywebapp
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  creationTimestamp: null
  name: mywebapp
spec:
  tls:
  - hosts: ['mywebapp.lab.local']
    secretName: mywebapp-tls
  rules:
  - host: mywebapp.lab.local
    http:
      paths:
      - backend:
          service:
            name: mywebapp
            port:
              number: 8080
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
